spring:
  jpa:
    show-sql: false
server:
  error:
    include-exception: false
cors:
  origins:
    - http://teambalanceapp-env.eba-sdy623yp.eu-central-1.elasticbeanstalk.com
    - http://localhost
